project: 
  type: website

website:
  title: "Andrew Belz's Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/your_url
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Andrew Belz 2024©"
    right: 
      - icon: linkedin
        href: www.linkedin.com/in/peter-belz-2aba70220

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "DS250 Projects"
        file: projects.qmd
      - text: "My Resume"
        file: resume.qmd
#      - text: "Data Cleansing"
#        file: cleansing.qmd
#      - text: "Data Exploration"
#        file: exploration.qmd
#      - text: "Story Telling"
#        file: story_telling.qmd
#      - text: "Machine Learning"
#        file: ml.qmd
#      - text: "Full Stack"
#        file: full_stack.qmd
#      - text: "Competition"
#        file: competition.qmd
      
  sidebar:
    - title: "DS 250 Projects"
      style: "docked"
      background: light
      contents:
        - text: "DS250 Projects"
          file: projects.qmd
        - text: "---"
        - text: "Project 1"
          file: Projects/proj.1.writeup.1.19.23.qmd
        - text: "---"
        - text: "Project 2"
          file: Projects/proj.2.writeup.2.7.24.qmd
        - text: "---"
        - text: "Project 3"
          file: Projects/proj.3.writeup.2.22.24.qmd
        - text: "---"
        - text: "Project 4"
          file: Projects/proj.4.writeup.3.2.24.qmd
        - text: "---"
        - text: "Project 5"
          file: Projects/proj.5.writeup.3.18.24.qmd
        - text: "---"
        #continue the pattern if you need more links
        #copy paste from title and keep it indented to sidebar to add additonal sidebar navigation for other pages

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



